version: "3.6"

services:
  app:
    image: app:latest
    container_name: application
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks:
      - my-network
    depends_on:
      redis_db:
        condition: service_healthy


  redis_db:
    image: redis/redis-stack-server:latest
    container_name: redis_db
    ports:
      - "6379:6378"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
    networks:
      - my-network

networks:
    my-network:
      driver: bridge

volumes:
  redis_data: